### ISSUE TITLE
panic when getting disk usage

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap-plugin-collector-docker#44]
**Snap version** (use `snapctl -v`):
test-4ac7b4d (docker container built from intelsdi/snap:xenial)

**Environment**:
- **Cloud provider or hardware configuration**: Running in Kubernetes on baremetal
- **OS** (e.g. from /etc/os-release): Ubuntu xenial
- **Kernel** (e.g. `uname -a`): 4.2.0-36-generic
- **Relevant tools** (e.g. plugins used with Snap):
- **Others** (e.g. deploying with Ansible): Docker version 1.12.1

**What happened**:
plugin panics and crashes.

**Steps to reproduce it** (as minimally and precisely as possible):

I am unsure of why the panic is being triggered. Perhaps a race condition where a path existed but removed before `du -s` is executed.  

**Anything else do we need to know** (e.g. issue happens only occasionally):
```
time="2016-11-07T10:27:12Z" level=debug msg="panic: runtime error: index out of range" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="goroutine 5 [running]:" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="panic(0x88dd40, 0xc420012090)" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="\t/home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:500 +0x1a1" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="github.com/intelsdi-x/snap-plugin-collector-docker/fs.diskUsage(0x9254e1, 0xf, 0xc42003aee8, 0xc42003ae78, 0x0)" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="\t/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-collector-docker/fs/fs.go:371 +0x177" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="github.com/intelsdi-x/snap-plugin-collector-docker/fs.(*DiskUsageCollector).worker.func1(0xb742f0, 0xc4200ffd00, 0x91dcac, 0x4, 0xc420012fd0, 0x1, 0x1)" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="\t/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-collector-docker/fs/fs.go:105 +0x449" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="created by github.com/intelsdi-x/snap-plugin-collector-docker/fs.(*DiskUsageCollector).worker" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
time="2016-11-07T10:27:12Z" level=debug msg="\t/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-collector-docker/fs/fs.go:119 +0x80" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker 
```

**Comment by IzabellaRaulin** [comment]
Thank You for reporting this issue.  As You mentioned, it might be related with a race condition where a path existed but removed before `du -s` is executed. I'll add bug label to it.

**Comment by daniellee** [comment]
This bug is a real problem for us so I investigated some more.

The first problem is that the error from the `du -s` command is swallowed causing a panic when an error does occur. I made a small change to log the error. 

Before: https://github.com/intelsdi-x/snap-plugin-collector-docker/blob/master/fs/fs.go#L370

```go
out, _ := exec.Command("du", "-s", dir).Output()
```

After:

```go
out, err := exec.Command("du", "-s", dir).Output()
 if err != nil {
     return 0, err
 }
```

This prevents the panic but spams the logs with lots of errors:

```bash
time="2016-11-17T19:25:22Z" level=debug msg="Cannot get usage for dir=`/var/lib/docker`, err=Disk usage not found for /var/lib/dockerCannot get usage for dir=`/var/lib/docker`, err=Disk usage not found for /var/lib/dockerCannot get usage for dir=`/var/lib/docker`, err=Disk usage not found for /var/lib/dockerWORKER root, ERROR {exit status 1} for /var/lib/docker" _module=plugin-exec io=stderr plugin=snap-plugin-collector-docker
```

Further investigation shows the real error (got by running `du -s /var/lib/docker` inside the container):

```bash
du: cannot access './proc_host/10353/task/10353/fd/26': No such file or directory
du: cannot access './proc_host/10353/task/10353/fd/27': No such file or directory
du: cannot access './proc_host/28373/task/28373/fd/4': No such file or directory
du: cannot access './proc_host/28373/task/28373/fdinfo/4': No such file or directory
du: cannot access './proc_host/28373/fd/3': No such file or directory
du: cannot access './proc_host/28373/fdinfo/3': No such file or directory
du: cannot access './proc_host/28378': No such file or directory
du: cannot access './proc/28373/task/28373/fd/4': No such file or directory
du: cannot access './proc/28373/task/28373/fdinfo/4': No such file or directory
du: cannot access './proc/28373/fd/3': No such file or directory
du: cannot access './proc/28373/fdinfo/3': No such file or directory
33149656
```

We are using [this docker image](https://hub.docker.com/r/raintank/snap_k8s/) with the following mounts (which is why proc_host is in the list of errors):

```docker
   volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /var/run/docker.sock
            name: docker-sock
          - mountPath: /var/lib/docker
            name: fs-stats
          - mountPath: /usr/local/bin/docker
            name: docker
          - mountPath: /proc_host
            name: proc
          - mountPath: /opt/snap/tasks
            name: snap-tasks
```

I'm not sure what the best solution is, maybe using the exclude argument with `du` e.g. `du -s --exclude=./proc*`

**Comment by woodsaj** [comment]
looks like most of these issues can be solved by simply passing the  "-x" argument to du.  This will prevent du from traversing into other fileystems that are mounted on top of the  target path.

```
